// const INLINE_ELEMENTS = require('eslint-plugin-vue/lib/utils/inline-non-void-elements.json');

module.exports = {
  extends: ['plugin:vue/recommended'],
  // required to lint *.vue files
  plugins: ['vue'],
  rules: {
    'vue/multi-word-component-names': 0,
    'vue/attribute-hyphenation': 0,
    'vue/require-prop-types': 1,
    'vue/block-spacing': 1,
    'vue/brace-style': 1,
    'vue/comma-dangle': [2, 'always-multiline'],
    'vue/component-definition-name-casing': [1, 'PascalCase'],
    'vue/html-end-tags': 2,
    'vue/html-quotes': 0,
    'vue/html-self-closing': [
      0,
      {
        html: {
          normal: 'never',
          void: 'never',
          component: 'never',
        },
        svg: 'always',
        math: 'always',
      },
    ],
    'vue/max-attributes-per-line': [
      0,
      {
        singleline: 1,
        multiline: {
          max: 1,
          allowFirstLine: false,
        },
      },
    ],
    'vue/mustache-interpolation-spacing': [1, 'always'],
    'vue/multiline-html-element-content-newline': [
      0,
      // {
      //   ignoreWhenEmpty: true,
      //   ignores: [
      //     'button',
      //     'el-button',
      //     'el-tag',
      //     'router-link',
      //     'pre',
      //     'textarea',
      //     ...INLINE_ELEMENTS,
      //   ],
      //   allowEmptyLines: false,
      // },
    ],
    // 'vue/name-property-casing': 0,
    'vue/no-async-in-computed-properties': 2,
    'vue/no-use-v-if-with-v-for': 2,
    'vue/no-deprecated-scope-attribute': 0,
    'vue/no-deprecated-slot-attribute': 0,
    'vue/no-deprecated-slot-scope-attribute': 0,

    'vue/no-dupe-keys': 2,
    'vue/no-duplicate-attributes': [
      2,
      {
        allowCoexistClass: true,
        allowCoexistStyle: true,
      },
    ],
    'vue/no-multi-spaces': 0,
    'vue/no-parsing-error': 2,
    'vue/no-reserved-component-names': 2,
    'vue/no-reserved-keys': [
      2,
      {
        reserved: ['$el', '$nextTick', '$route', '$router', 'asyncData'],
        groups: [],
      },
    ],
    'vue/no-shared-component-data': 2,
    'vue/no-side-effects-in-computed-properties': 2,
    'vue/no-static-inline-styles': 1,
    'vue/no-template-key': 2,
    'vue/no-template-shadow': 2,
    'vue/no-textarea-mustache': 2,
    'vue/no-unused-vars': 1,
    'vue/no-unused-components': 1,
    'vue/no-v-html': 1,
    'vue/component-tags-order': 0,
    'vue/order-in-components': [
      1,
      {
        order: [
          ['name', 'delimiters', 'functional', 'model'],
          'asyncData',
          ['components', 'directives', 'filters'],
          ['parent', 'mixins', 'extends', 'provide', 'inject'],
          'el',
          'template',
          'props',
          'propsData',
          'data',
          'computed',
          'watch',
          'onWechatReady',
          'LIFECYCLE_HOOKS',
          'methods',
          'render',
          'renderError',
        ],
      },
    ],
    'vue/padding-line-between-blocks': 1,
    'vue/require-component-is': 2,
    'vue/require-default-prop': 0,
    'vue/require-name-property': 0,
    // 'vue/require-prop-types': 2,
    'vue/require-render-return': 2,
    'vue/require-v-for-key': 2,
    // 'vue/require-valid-default-prop': 2,
    'vue/return-in-computed-property': 2,
    'vue/html-indent': 0,
    'vue/script-indent': 0,
    'vue/singleline-html-element-content-newline': 0,
    'vue/space-infix-ops': 2,
    'vue/this-in-template': [2, 'never'],
    'vue/v-bind-style': [2, 'shorthand'],
    'vue/v-on-style': [2, 'shorthand'],
    'vue/v-slot-style': [
      2,
      {
        atComponent: 'shorthand',
        default: 'shorthand',
        named: 'shorthand',
      },
    ],
    'vue/valid-template-root': 2,
    'vue/valid-v-bind': 2,
    'vue/valid-v-bind-sync': 2,
    'vue/valid-v-cloak': 2,
    'vue/valid-v-else': 2,
    'vue/valid-v-else-if': 2,
    'vue/valid-v-for': 2,
    'vue/valid-v-html': 2,
    'vue/valid-v-if': 2,
    'vue/valid-v-model': 2,
    'vue/valid-v-on': 2,
    'vue/valid-v-once': 2,
    'vue/valid-v-pre': 2,
    'vue/valid-v-show': 2,
    'vue/valid-v-slot': 2,
    'vue/valid-v-text': 2,
  },
  overrides: [
    {
      files: ['*.vue'],
      rules: {
        indent: 0,
      },
    },
  ],
};
